# Generated by Django 4.1.1 on 2022-09-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
